# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Headcalc <- function(Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakebedgrid, Lakecondgrid, GWETgrid, Classgrid, Timestep, Runtime, ETexdepth, Lakedepth, Cellxdim, Cellydim, Accuracy, Maxiterations, GWNumbers) {
    .Call(`_CHIMBLERcpp_Headcalc`, Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakebedgrid, Lakecondgrid, GWETgrid, Classgrid, Timestep, Runtime, ETexdepth, Lakedepth, Cellxdim, Cellydim, Accuracy, Maxiterations, GWNumbers)
}

func_ClassGrid <- function(Time, Topogrid, LakeDepths, GWcatchmentgrid, Classgrid, Lakevolumes) {
    invisible(.Call(`_CHIMBLERcpp_func_ClassGrid`, Time, Topogrid, LakeDepths, GWcatchmentgrid, Classgrid, Lakevolumes))
}

func_LakeConductance <- function(Lakecondgrid, Cellxdim, Cellydim, GWlakesedimentgrid, GWlakekgrid) {
    invisible(.Call(`_CHIMBLERcpp_func_LakeConductance`, Lakecondgrid, Cellxdim, Cellydim, GWlakesedimentgrid, GWlakekgrid))
}

func_RechargeGrid <- function(Time, Cellxdim, Cellydim, GWRechargegrid, Classgrid, Flux, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_RechargeGrid`, Time, Cellxdim, Cellydim, GWRechargegrid, Classgrid, Flux, Timestep))
}

func_ETGrid <- function(Time, GWETgrid, Flux) {
    invisible(.Call(`_CHIMBLERcpp_func_ETGrid`, Time, GWETgrid, Flux))
}

func_LakeDepths <- function(Lake, Time, LakeDepths) {
    invisible(.Call(`_CHIMBLERcpp_func_LakeDepths`, Lake, Time, LakeDepths))
}

func_CAe <- function(CA, Lake, Time) {
    .Call(`_CHIMBLERcpp_func_CAe`, CA, Lake, Time)
}

func_FpLake <- function(Time, Met, Lake, Timestep) {
    .Call(`_CHIMBLERcpp_func_FpLake`, Time, Met, Lake, Timestep)
}

func_Fsm <- function(CA, Time, Lake, Met, Isotopes, Datarate, Timestep) {
    .Call(`_CHIMBLERcpp_func_Fsm`, CA, Time, Lake, Met, Isotopes, Datarate, Timestep)
}

func_Fext <- function(Time, Met, Isotopes, Timestep) {
    .Call(`_CHIMBLERcpp_func_Fext`, Time, Met, Isotopes, Timestep)
}

func_Fgw <- function(Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakesedimentgrid, Lakecondgrid, GWETgrid, Classgrid, Timestep, ETexdepth, Cellxdim, Cellydim, Accuracy, Maxiterations, Time, Lake, GWcatchmentgrid, Lakevolumes, GWlakekgrid, Flux, LakeDepths, Csr, Met, Isotopes, GroundwaterModule, GWStats, GWNumbers, GWLakeID) {
    .Call(`_CHIMBLERcpp_func_Fgw`, Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakesedimentgrid, Lakecondgrid, GWETgrid, Classgrid, Timestep, ETexdepth, Cellxdim, Cellydim, Accuracy, Maxiterations, Time, Lake, GWcatchmentgrid, Lakevolumes, GWlakekgrid, Flux, LakeDepths, Csr, Met, Isotopes, GroundwaterModule, GWStats, GWNumbers, GWLakeID)
}

func_FpCatchment <- function(Time, Met, CA, Lake, Timestep) {
    .Call(`_CHIMBLERcpp_func_FpCatchment`, Time, Met, CA, Lake, Timestep)
}

func_DayofYear <- function(Month, Day) {
    .Call(`_CHIMBLERcpp_func_DayofYear`, Month, Day)
}

CDaysInMonth <- function(Month, Year) {
    .Call(`_CHIMBLERcpp_CDaysInMonth`, Month, Year)
}

func_MonthFraction <- function(Time, Met, Datarate, Timestep) {
    .Call(`_CHIMBLERcpp_func_MonthFraction`, Time, Met, Datarate, Timestep)
}

func_Ra <- function(Time, LatitudeRadians, Met) {
    .Call(`_CHIMBLERcpp_func_Ra`, Time, LatitudeRadians, Met)
}

func_E <- function(Time, Met, ALBlake, PWF, LatitudeRadians, Datarate, Timestep, ChemConcentrations, StratificationModule, NeutralDragCoeff, Feedback) {
    .Call(`_CHIMBLERcpp_func_E`, Time, Met, ALBlake, PWF, LatitudeRadians, Datarate, Timestep, ChemConcentrations, StratificationModule, NeutralDragCoeff, Feedback)
}

func_PET <- function(Time, Met, ALBearth, PWF, LatitudeRadians, Datarate, Timestep) {
    .Call(`_CHIMBLERcpp_func_PET`, Time, Met, ALBearth, PWF, LatitudeRadians, Datarate, Timestep)
}

func_Evap <- function(CA, Time, Met, Lake, Isotopes, AWCss, AWCds, KcDS, LatitudeRadians, KcSS, ALBearth, ALBlake, Datarate, PWF, Timestep) {
    .Call(`_CHIMBLERcpp_func_Evap`, CA, Time, Met, Lake, Isotopes, AWCss, AWCds, KcDS, LatitudeRadians, KcSS, ALBearth, ALBlake, Datarate, PWF, Timestep)
}

func_Soil <- function(Time, AWCss, AWCds, CA, Lake, Met, Isotopes, KcDS, KcSS, LatitudeRadians, RunoffRatio, ALBearth, ALBlake, PWF, Datarate, Timestep) {
    .Call(`_CHIMBLERcpp_func_Soil`, Time, AWCss, AWCds, CA, Lake, Met, Isotopes, KcDS, KcSS, LatitudeRadians, RunoffRatio, ALBearth, ALBlake, PWF, Datarate, Timestep)
}

func_Fsf <- function(CA, Lake, Time, Met, Timestep) {
    .Call(`_CHIMBLERcpp_func_Fsf`, CA, Lake, Time, Met, Timestep)
}

func_Fin <- function(CA, Lake, Time, Isotopes, Cin, Timestep) {
    .Call(`_CHIMBLERcpp_func_Fin`, CA, Lake, Time, Isotopes, Cin, Timestep)
}

func_SVC <- function(Time, Met, Lakevolumes, Lake, Interpolationtype) {
    .Call(`_CHIMBLERcpp_func_SVC`, Time, Met, Lakevolumes, Lake, Interpolationtype)
}

func_Fdlm <- function(Time, Isotopes, Met, Lakevolumes, Lake, Interpolationtype) {
    .Call(`_CHIMBLERcpp_func_Fdlm`, Time, Isotopes, Met, Lakevolumes, Lake, Interpolationtype)
}

func_KcLake <- function(Time, KcLwin, KcLsum, Met, Datarate, Timestep) {
    .Call(`_CHIMBLERcpp_func_KcLake`, Time, KcLwin, KcLsum, Met, Datarate, Timestep)
}

func_Fe <- function(Time, Timestep, Lake, Met, ALBlake, Isotopes, PWF, LatitudeRadians, Datarate, KcLwin, KcLsum, ChemConcentrations, StratificationModule, NeutralDragCoeff, Feedback) {
    .Call(`_CHIMBLERcpp_func_Fe`, Time, Timestep, Lake, Met, ALBlake, Isotopes, PWF, LatitudeRadians, Datarate, KcLwin, KcLsum, ChemConcentrations, StratificationModule, NeutralDragCoeff, Feedback)
}

func_FeedbackRH <- function(Met, Time, Feedback) {
    .Call(`_CHIMBLERcpp_func_FeedbackRH`, Met, Time, Feedback)
}

func_Fof <- function(Lake, Lakevolumes, Time) {
    .Call(`_CHIMBLERcpp_func_Fof`, Lake, Lakevolumes, Time)
}

func_Lakearea <- function(Volume, Lakevolumes) {
    .Call(`_CHIMBLERcpp_func_Lakearea`, Volume, Lakevolumes)
}

func_Lakedepth <- function(Volume, Lakevolumes) {
    .Call(`_CHIMBLERcpp_func_Lakedepth`, Volume, Lakevolumes)
}

func_Lakevolume <- function(Depth, Lakevolumes) {
    .Call(`_CHIMBLERcpp_func_Lakevolume`, Depth, Lakevolumes)
}

func_dE <- function(Time, Isotype, Isotopes, Met, AtmosphericShift, Turbulence, Feedback, Lakevolumes, Lake, Interpolationtype, ChemConcentrations, Theta) {
    .Call(`_CHIMBLERcpp_func_dE`, Time, Isotype, Isotopes, Met, AtmosphericShift, Turbulence, Feedback, Lakevolumes, Lake, Interpolationtype, ChemConcentrations, Theta)
}

RH_Normalised <- function(Met, Time, Feedback, Act_Water, tLake) {
    .Call(`_CHIMBLERcpp_RH_Normalised`, Met, Time, Feedback, Act_Water, tLake)
}

StrSplitFront <- function(StringToSplit, Delim) {
    .Call(`_CHIMBLERcpp_StrSplitFront`, StringToSplit, Delim)
}

StrSplitBack <- function(StringToSplit, Delim) {
    .Call(`_CHIMBLERcpp_StrSplitBack`, StringToSplit, Delim)
}

func_FluxFpCatchment <- function(Flux, Met, Time, CA, Lake, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFpCatchment`, Flux, Met, Time, CA, Lake, Timestep))
}

func_FluxFpLake <- function(Flux, Time, Met, Lake, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFpLake`, Flux, Time, Met, Lake, Timestep))
}

func_FluxFe <- function(Flux, Time, Timestep, Lake, Met, ALBlake, Isotopes, PWF, LatitudeRadians, Datarate, KcLwin, KcLsum, ChemConcentrations, StratificationModule, NeutralDragCoeff, Feedback) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFe`, Flux, Time, Timestep, Lake, Met, ALBlake, Isotopes, PWF, LatitudeRadians, Datarate, KcLwin, KcLsum, ChemConcentrations, StratificationModule, NeutralDragCoeff, Feedback))
}

func_FluxFsm <- function(Flux, CA, Time, Lake, Met, Isotopes, Datarate, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFsm`, Flux, CA, Time, Lake, Met, Isotopes, Datarate, Timestep))
}

func_FluxFext <- function(Flux, Time, Met, Isotopes, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFext`, Flux, Time, Met, Isotopes, Timestep))
}

func_FluxFdlm <- function(Flux, Time, Isotopes, Met, Lakevolumes, Lake, Interpolationtype) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFdlm`, Flux, Time, Isotopes, Met, Lakevolumes, Lake, Interpolationtype))
}

func_FluxSoil <- function(Flux, Time, AWCss, AWCds, CA, Lake, Met, Isotopes, KcDS, KcSS, LatitudeRadians, RunoffRatio, ALBearth, ALBlake, PWF, Datarate, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxSoil`, Flux, Time, AWCss, AWCds, CA, Lake, Met, Isotopes, KcDS, KcSS, LatitudeRadians, RunoffRatio, ALBearth, ALBlake, PWF, Datarate, Timestep))
}

func_FluxSoilEvap <- function(Flux, CA, Time, Met, Lake, Isotopes, AWCss, AWCds, KcDS, LatitudeRadians, KcSS, ALBearth, ALBlake, Datarate, PWF, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxSoilEvap`, Flux, CA, Time, Met, Lake, Isotopes, AWCss, AWCds, KcDS, LatitudeRadians, KcSS, ALBearth, ALBlake, Datarate, PWF, Timestep))
}

func_FluxFin <- function(Flux, CA, Lake, Time, Isotopes, Cin, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFin`, Flux, CA, Lake, Time, Isotopes, Cin, Timestep))
}

func_FluxFsf <- function(Flux, CA, Lake, Time, Met, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFsf`, Flux, CA, Lake, Time, Met, Timestep))
}

func_FluxFgw <- function(Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakesedimentgrid, Lakecondgrid, GWETgrid, Classgrid, Timestep, ETexdepth, Cellxdim, Cellydim, Accuracy, Maxiterations, Time, Lake, GWcatchmentgrid, Lakevolumes, GWlakekgrid, Flux, LakeDepths, Csr, Met, Isotopes, GroundwaterModule, GWStats, GWNumbers, GWLakeID) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFgw`, Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakesedimentgrid, Lakecondgrid, GWETgrid, Classgrid, Timestep, ETexdepth, Cellxdim, Cellydim, Accuracy, Maxiterations, Time, Lake, GWcatchmentgrid, Lakevolumes, GWlakekgrid, Flux, LakeDepths, Csr, Met, Isotopes, GroundwaterModule, GWStats, GWNumbers, GWLakeID))
}

func_FluxFof <- function(Flux, Lake, Lakevolumes, Time) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxFof`, Flux, Lake, Lakevolumes, Time))
}

func_FluxE <- function(Flux, Time, Met, ALBlake, PWF, LatitudeRadians, Datarate, Timestep, ChemConcentrations, StratificationModule, NeutralDragCoeff, Feedback) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxE`, Flux, Time, Met, ALBlake, PWF, LatitudeRadians, Datarate, Timestep, ChemConcentrations, StratificationModule, NeutralDragCoeff, Feedback))
}

func_FluxPET <- function(Flux, Time, Met, ALBearth, PWF, LatitudeRadians, Datarate, Timestep) {
    invisible(.Call(`_CHIMBLERcpp_func_FluxPET`, Flux, Time, Met, ALBearth, PWF, LatitudeRadians, Datarate, Timestep))
}

func_Fluxes <- function(KcSS, ALBearth, ALBlake, CA, Cin, Csr, KcDS, KcLsum, KcLwin, LatitudeRadians, RunoffRatio, PWF, Timestep, AWCds, AWCss, Time, Flux, Isotopes, Lake, Met, Lakevolumes, Datarate, Interpolationtype, GroundwaterModule, Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakesedimentgrid, Lakecondgrid, GWETgrid, Classgrid, ETexdepth, Cellxdim, Cellydim, Accuracy, Maxiterations, GWcatchmentgrid, GWlakekgrid, LakeDepths, GWStats, GWNumbers, ChemConcentrations, StratificationModule, NeutralDragCoeff, GWLakeID, Feedback) {
    invisible(.Call(`_CHIMBLERcpp_func_Fluxes`, KcSS, ALBearth, ALBlake, CA, Cin, Csr, KcDS, KcLsum, KcLwin, LatitudeRadians, RunoffRatio, PWF, Timestep, AWCds, AWCss, Time, Flux, Isotopes, Lake, Met, Lakevolumes, Datarate, Interpolationtype, GroundwaterModule, Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakesedimentgrid, Lakecondgrid, GWETgrid, Classgrid, ETexdepth, Cellxdim, Cellydim, Accuracy, Maxiterations, GWcatchmentgrid, GWlakekgrid, LakeDepths, GWStats, GWNumbers, ChemConcentrations, StratificationModule, NeutralDragCoeff, GWLakeID, Feedback))
}

func_Hydrology <- function(Flux, Lake, Isotopes, Time, Met, Lakevolumes, Interpolationtype, DirectExternalFlows, GroundwaterModule, GWStats) {
    invisible(.Call(`_CHIMBLERcpp_func_Hydrology`, Flux, Lake, Isotopes, Time, Met, Lakevolumes, Interpolationtype, DirectExternalFlows, GroundwaterModule, GWStats))
}

func_IsotopeFluxes <- function(Flux, Time, Isotopes, Met, AtmosphericShift, Turbulence, Feedback, Lakevolumes, Lake, Interpolationtype, DirectExternalFlows, FluxD, Flux18O, GroundwaterModule, GWStats, GWNumbers, ChemConcentrations, Theta) {
    invisible(.Call(`_CHIMBLERcpp_func_IsotopeFluxes`, Flux, Time, Isotopes, Met, AtmosphericShift, Turbulence, Feedback, Lakevolumes, Lake, Interpolationtype, DirectExternalFlows, FluxD, Flux18O, GroundwaterModule, GWStats, GWNumbers, ChemConcentrations, Theta))
}

func_ChemistryFluxes <- function(Chemistry, Time, Flux, Lake, Met, DirectExternalFlows, GroundwaterModule, GWStats, GWNumbers) {
    invisible(.Call(`_CHIMBLERcpp_func_ChemistryFluxes`, Chemistry, Time, Flux, Lake, Met, DirectExternalFlows, GroundwaterModule, GWStats, GWNumbers))
}

func_LakeMixer <- function(Flux, Lake, Chemistry, Isotopes, Time, Met, Lakevolumes, Interpolationtype, FluxD, Flux18O) {
    invisible(.Call(`_CHIMBLERcpp_func_LakeMixer`, Flux, Lake, Chemistry, Isotopes, Time, Met, Lakevolumes, Interpolationtype, FluxD, Flux18O))
}

MassBalance <- function(KcSS, ALBearth, ALBlake, CA, Cin, Csr, KcDS, KcLsum, KcLwin, LatitudeRadians, RunoffRatio, PWF, Timestep, AWCds, AWCss, Time, Flux, Isotopes, Lake, Met, Lakevolumes, Datarate, Interpolationtype, GroundwaterModule, Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakesedimentgrid, Lakecondgrid, GWETgrid, Classgrid, ETexdepth, Cellxdim, Cellydim, Accuracy, Maxiterations, GWcatchmentgrid, GWlakekgrid, LakeDepths, Chemistry, DirectExternalFlows, AtmosphericShift, Turbulence, Feedback, FluxD, Flux18O, GWStats, GWNumbers, ScenarioEventsList, ScenarioEvents, ChemConcentrations, ChemParams, NeutralDragCoeff, SWExtCoef, ThermoclineTargetThickness, ThermoclineMaximum, StratificationModule, Stratification, GWLakeID, Theta) {
    invisible(.Call(`_CHIMBLERcpp_MassBalance`, KcSS, ALBearth, ALBlake, CA, Cin, Csr, KcDS, KcLsum, KcLwin, LatitudeRadians, RunoffRatio, PWF, Timestep, AWCds, AWCss, Time, Flux, Isotopes, Lake, Met, Lakevolumes, Datarate, Interpolationtype, GroundwaterModule, Topogrid, GWRechargegrid, GWPumpinggrid, GWKgrid, GWSgrid, GWbasegrid, GWheadgrid, GWboundarygrid, GWlakesedimentgrid, Lakecondgrid, GWETgrid, Classgrid, ETexdepth, Cellxdim, Cellydim, Accuracy, Maxiterations, GWcatchmentgrid, GWlakekgrid, LakeDepths, Chemistry, DirectExternalFlows, AtmosphericShift, Turbulence, Feedback, FluxD, Flux18O, GWStats, GWNumbers, ScenarioEventsList, ScenarioEvents, ChemConcentrations, ChemParams, NeutralDragCoeff, SWExtCoef, ThermoclineTargetThickness, ThermoclineMaximum, StratificationModule, Stratification, GWLakeID, Theta))
}

CalcMolarities <- function(Time, Chemistry, ChemConcentrations) {
    invisible(.Call(`_CHIMBLERcpp_CalcMolarities`, Time, Chemistry, ChemConcentrations))
}

EstimateSaltMolarities <- function(ChemConcentrations) {
    invisible(.Call(`_CHIMBLERcpp_EstimateSaltMolarities`, ChemConcentrations))
}

CalcSalts <- function(ChemConcentrations) {
    invisible(.Call(`_CHIMBLERcpp_CalcSalts`, ChemConcentrations))
}

CalcSaltDensity <- function(ChemConcentrations, ChemParams) {
    invisible(.Call(`_CHIMBLERcpp_CalcSaltDensity`, ChemConcentrations, ChemParams))
}

CalcWaterActivity <- function(ChemConcentrations, ChemParams) {
    invisible(.Call(`_CHIMBLERcpp_CalcWaterActivity`, ChemConcentrations, ChemParams))
}

SalinityCalcs <- function(Time, ChemConcentrations, Chemistry, ChemParams) {
    invisible(.Call(`_CHIMBLERcpp_SalinityCalcs`, Time, ChemConcentrations, Chemistry, ChemParams))
}

func_Density <- function(LakeTemperature, Salinity) {
    .Call(`_CHIMBLERcpp_func_Density`, LakeTemperature, Salinity)
}

func_LakeDrag <- function(LakeTemperature, AirTemperature, WindSpeed, NeutralDragCoeff) {
    .Call(`_CHIMBLERcpp_func_LakeDrag`, LakeTemperature, AirTemperature, WindSpeed, NeutralDragCoeff)
}

func_LakeAlbedo <- function(Julian, LatitudeRadians) {
    .Call(`_CHIMBLERcpp_func_LakeAlbedo`, Julian, LatitudeRadians)
}

func_IceAlbedo <- function(AirTemperature, FreezingTemp) {
    .Call(`_CHIMBLERcpp_func_IceAlbedo`, AirTemperature, FreezingTemp)
}

func_SnowAlbedo <- function(MeltFlag) {
    .Call(`_CHIMBLERcpp_func_SnowAlbedo`, MeltFlag)
}

func_Teten <- function(Temperature) {
    .Call(`_CHIMBLERcpp_func_Teten`, Temperature)
}

func_LatSensHeat <- function(LakeTemperature, AirTemperature, WindSpeed, LakeIceThickness, FreezingTemp, SurfacePressure, RH, NeutralDragCoeff) {
    .Call(`_CHIMBLERcpp_func_LatSensHeat`, LakeTemperature, AirTemperature, WindSpeed, LakeIceThickness, FreezingTemp, SurfacePressure, RH, NeutralDragCoeff)
}

func_SpecificHeat <- function(LakeTemperature, Salinity) {
    .Call(`_CHIMBLERcpp_func_SpecificHeat`, LakeTemperature, Salinity)
}

TridiagSolver <- function(NumSystems, Columns, NumUnknowns, SubdiagMatrix, MainDiagMatrix, SuperDiagMatrix, RHS) {
    .Call(`_CHIMBLERcpp_TridiagSolver`, NumSystems, Columns, NumUnknowns, SubdiagMatrix, MainDiagMatrix, SuperDiagMatrix, RHS)
}

func_IceSWRad <- function(SW, LakeIceThickness, SnowThickness) {
    .Call(`_CHIMBLERcpp_func_IceSWRad`, SW, LakeIceThickness, SnowThickness)
}

func_FreezingPoint <- function(SurfacePressure, Salinity) {
    .Call(`_CHIMBLERcpp_func_FreezingPoint`, SurfacePressure, Salinity)
}

func_OldDownwardLongwave <- function(Ra, Rs, AirTemperature, WaterVaporPressure) {
    .Call(`_CHIMBLERcpp_func_OldDownwardLongwave`, Ra, Rs, AirTemperature, WaterVaporPressure)
}

func_DownwardLongwave <- function(Time, LatitudeRadians, Met) {
    .Call(`_CHIMBLERcpp_func_DownwardLongwave`, Time, LatitudeRadians, Met)
}

func_LongWave <- function(LakeIceThickness, WaterTemperature, TempIce, Ra, Rs, AirTemperature, RH, Met, Time, LatitudeRadians) {
    .Call(`_CHIMBLERcpp_func_LongWave`, LakeIceThickness, WaterTemperature, TempIce, Ra, Rs, AirTemperature, RH, Met, Time, LatitudeRadians)
}

func_TempProfile <- function(LakeIceThickness, LakeDepth, LakeSurfaceArea, LakeTemperature, AirTemperature, WindSpeed, SurfacePressure, RH, Salinity, TempIce, Ra, Rs, LatitudeRadians, Julian, Stratification, NeutralDragCoeff, SWExtCoef, Met, Time) {
    invisible(.Call(`_CHIMBLERcpp_func_TempProfile`, LakeIceThickness, LakeDepth, LakeSurfaceArea, LakeTemperature, AirTemperature, WindSpeed, SurfacePressure, RH, Salinity, TempIce, Ra, Rs, LatitudeRadians, Julian, Stratification, NeutralDragCoeff, SWExtCoef, Met, Time))
}

func_ConvectionMixing <- function(Stratification, LakeDepth) {
    invisible(.Call(`_CHIMBLERcpp_func_ConvectionMixing`, Stratification, LakeDepth))
}

func_Interpolate <- function(StartValue, EndValue, Days, CurrentDay) {
    .Call(`_CHIMBLERcpp_func_Interpolate`, StartValue, EndValue, Days, CurrentDay)
}

func_CleanAirAct <- function(Stratification, LakeDepth) {
    .Call(`_CHIMBLERcpp_func_CleanAirAct`, Stratification, LakeDepth)
}

func_RunStratification <- function(Time, Met, Lake, ChemConcentrations, Stratification, LatitudeRadians, NeutralDragCoeff, SWExtCoef, ThermoclineTargetThickness, ThermoclineMaximum, Feedback) {
    invisible(.Call(`_CHIMBLERcpp_func_RunStratification`, Time, Met, Lake, ChemConcentrations, Stratification, LatitudeRadians, NeutralDragCoeff, SWExtCoef, ThermoclineTargetThickness, ThermoclineMaximum, Feedback))
}

